class eSlider: public eWidget {
  sf::Texture* tinstBack;
  sf::Texture* tinstHandle;
  sf::Sprite sinstBack;
  sf::Sprite sinstHandle;
  eColor bcolor, hcolor;
  float highlight;
  int curType;
  double min, max;
  double* val;
  void (*holdCallback)();
  void (*releaseCallback)();
  void (*valueCallback)();
  double hxo, hyo;
  double hrad;
  int hfw, hfh;
  bool clicked, active;
  std::vector<double> attPoints;
  public:
    XPT int init();
    XPT int setHandleSize(double rad);
    XPT int setSize(double w, double h);
    XPT int setRange(double min, double max);
    XPT int setTrack(double& val);
    XPT int setBackColor(eColor col);
    XPT int setHandleColor(eColor col);
    XPT int event(eEvent& ev);
    XPT int setHoldCallback(void (*callback)());
    XPT int setReleaseCallback(void (*callback)());
    XPT int setValueCallback(void (*callback)());
    XPT int addAttPoint(double val);
    XPT int delAttPoint(int which);
    XPT double getAttPoint(int which);
    XPT int attPointCount();
    XPT int update();
    XPT int draw();
};
